baseurl = "http://golangbcn.org/"
contentdir = "content"
publishdir = "public"
title = "Gophers in BCN"
author = "GolangBCN meetup group"
copyright = "<a rel='license' href='http://creativecommons.org/licenses/by-sa/4.0/'><img alt='Creative Commons License' style='border-width:0; width:44; height:16;' src='https://i.creativecommons.org/l/by-sa/4.0/88x31.png' /></a><br />This work is licensed under a <a rel='license' href='http://creativecommons.org/licenses/by-sa/4.0/'>Creative Commons Attribution-ShareAlike 4.0 International License</a>."
languagecode = "en-US"
canonifyurls = true

[params]
    Descripion = "GolangBCN Group's Blog"
    github = "GolangBCN"
    twitter = "GolangBCN"
